In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from utility_functions import *

c:\Users\17327\AppData\Local\Programs\Python\Python310\lib\site-packages\scipy\__init__.py:169: UserWarning: A NumPy version >=1.18.5 and <1.26.0 is required for this version of SciPy (detected version 1.26.1
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [2]:
velocity_df = pd.read_excel('../../Data/data_16_runs/Data_Input.xlsx', sheet_name = 'v_axial')
velocity_df.head()

,z,ax: 5_45,ax: 5_55,ax: 5_65,ax: 5_75,ax: 3_45,ax: 4_45,ax: 5_45.1,ax: 6_45,ax: 3_55,ax: 3_65,ax: 3_75,ax: 6_55,ax: 6_65,ax: 6_75,ax: 4_55,ax: 4_65,ax: 4_75
0,-0.205076,0.001939,0.002848,0.001564,0.002415,0.002834,0.002917,0.000234,0.000195,0.000829,0.001346,0.002669,0.001539,-0.000282,0.000803,0.001423,0.003550,0.001217
1,-0.200122,0.003104,0.002224,0.002254,0.002303,0.003024,0.003172,0.000899,0.001147,0.001214,0.001492,0.003175,0.002488,0.001111,0.001542,0.002275,0.003804,0.002329
2,-0.195160,0.003236,0.002293,0.002683,0.002356,0.002442,0.002872,0.001109,0.001594,0.001438,0.001592,0.002533,0.003265,0.001659,0.001689,0.002932,0.002881,0.003083
3,-0.190173,0.002337,0.002356,0.003154,0.002886,0.002050,0.002421,0.001017,0.001624,0.001624,0.001266,0.002006,0.003434,0.001555,0.001556,0.002983,0.002189,0.002663
4,-0.185151,0.001783,0.002605,0.002524,0.003820,0.002345,0.002418,0.000932,0.001825,0.001548,0.002003,0.002469,0.003054,0.001187,0.002137,0.002315,0.002919,0.002031

In [3]:
velocity_df.shape

(244, 18)

In [4]:
# velocity_df = velocity_df.drop('ax: 5_45.1', axis = 1)
# velocity_df.head()

In [5]:
# velocity_df.shape

In [6]:
velocity_df = velocity_df[(velocity_df['z'] >= 0) & (velocity_df['z'] <= 1)]
velocity_df.shape

(181, 18)

In [7]:
velocity_df = velocity_df.reset_index(drop = True)

In [8]:
velocity_df.head()

,z,ax: 5_45,ax: 5_55,ax: 5_65,ax: 5_75,ax: 3_45,ax: 4_45,ax: 5_45.1,ax: 6_45,ax: 3_55,ax: 3_65,ax: 3_75,ax: 6_55,ax: 6_65,ax: 6_75,ax: 4_55,ax: 4_65,ax: 4_75
0,0.004722,0.003371,0.003013,0.003419,0.004706,0.002364,0.003059,0.003075,0.002729,0.003014,0.002934,0.002085,0.003895,0.004702,0.003811,0.002989,0.002387,0.004429
1,0.010347,0.003227,0.003697,0.003598,0.004513,0.002188,0.002993,0.003032,0.001742,0.002499,0.002958,0.002479,0.003892,0.004636,0.004089,0.003337,0.002572,0.004278
2,0.015973,0.003662,0.004054,0.003357,0.004830,0.002157,0.002863,0.002735,0.001849,0.002443,0.003052,0.002891,0.003863,0.004736,0.003687,0.003696,0.002954,0.003731
3,0.021597,0.003778,0.004445,0.003517,0.004803,0.002319,0.003085,0.002164,0.002360,0.003043,0.002848,0.003506,0.003825,0.003792,0.003900,0.003152,0.003554,0.002856
4,0.027219,0.003397,0.004099,0.003562,0.004806,0.002511,0.003146,0.002091,0.002932,0.002950,0.002503,0.004006,0.004237,0.003381,0.004324,0.002130,0.003871,0.002831

In [9]:
velocity_df.tail()

,z,ax: 5_45,ax: 5_55,ax: 5_65,ax: 5_75,ax: 3_45,ax: 4_45,ax: 5_45.1,ax: 6_45,ax: 3_55,ax: 3_65,ax: 3_75,ax: 6_55,ax: 6_65,ax: 6_75,ax: 4_55,ax: 4_65,ax: 4_75
176,0.973297,0.001503,0.001289,0.001485,0.001232,0.000949,0.001158,0.001474,0.001583,0.001084,0.001264,0.001062,0.001748,0.001878,0.001508,0.001216,0.000875,0.001452
177,0.978715,0.001506,0.001432,0.001570,0.001348,0.000921,0.001104,0.001461,0.001587,0.001041,0.001254,0.000993,0.001735,0.001904,0.001439,0.001224,0.000914,0.001469
178,0.984133,0.001476,0.001357,0.001531,0.001359,0.000709,0.000916,0.001472,0.001574,0.001062,0.001237,0.000632,0.001780,0.001964,0.001404,0.001245,0.000813,0.001439
179,0.989551,0.001450,0.001315,0.001487,0.001321,0.000725,0.000922,0.001483,0.001571,0.001114,0.001229,0.000647,0.001761,0.001965,0.001481,0.001283,0.000825,0.001482
180,0.994969,0.001477,0.001408,0.001509,0.001335,0.000930,0.001112,0.001458,0.001604,0.001099,0.001279,0.001002,0.001798,0.001939,0.001429,0.001266,0.001061,0.001429

Application of Locally Weighted Scatterplot Smoothing(LOWESS)

In [10]:
X = velocity_df['z']

data = {'z':X}

for col in velocity_df.columns[1:]:
    y = velocity_df[col]
    yest = cleveland_lowess(X, y, f = 0.5, iter = 3)
    data[col] = yest

smoothed_velocities = pd.DataFrame(data)
smoothed_velocities.head()

,z,ax: 5_45,ax: 5_55,ax: 5_65,ax: 5_75,ax: 3_45,ax: 4_45,ax: 5_45.1,ax: 6_45,ax: 3_55,ax: 3_65,ax: 3_75,ax: 6_55,ax: 6_65,ax: 6_75,ax: 4_55,ax: 4_65,ax: 4_75
0,0.004722,0.003191,0.003278,0.003597,0.004010,0.002332,0.002869,0.003086,0.003365,0.002755,0.002535,0.002795,0.003757,0.003988,0.004023,0.003032,0.003303,0.003267
1,0.010347,0.003165,0.003259,0.003570,0.003976,0.002315,0.002849,0.003069,0.003336,0.002735,0.002514,0.002775,0.003727,0.003962,0.003991,0.003011,0.003277,0.003242
2,0.015973,0.003139,0.003241,0.003544,0.003942,0.002298,0.002829,0.003052,0.003308,0.002715,0.002493,0.002754,0.003697,0.003937,0.003959,0.002990,0.003252,0.003218
3,0.021597,0.003113,0.003222,0.003517,0.003909,0.002281,0.002809,0.003034,0.003279,0.002695,0.002473,0.002734,0.003668,0.003911,0.003926,0.002969,0.003226,0.003194
4,0.027219,0.003087,0.003203,0.003491,0.003876,0.002264,0.002790,0.003017,0.003251,0.002675,0.002453,0.002715,0.003639,0.003886,0.003894,0.002948,0.003201,0.003170

In [11]:
# smoothed_velocities.to_csv('../../Data/data_16_runs/smoothed_velocities.csv', index = False)
# smoothed_velocities.to_csv('../../Data/data_16_runs/v_data16.csv', index = False)

Dataset preparation for Axial Velocity prediction

In [12]:
axial_velocity_df = make_axial_velocity_data(smoothed_velocities)
axial_velocity_df.head()

          z  Q   RPM  axial_velocity
0  0.004722  5  45.0        0.003191
1  0.010347  5  45.0        0.003165
2  0.015973  5  45.0        0.003139
3  0.021597  5  45.0        0.003113
4  0.027219  5  45.0        0.003087

In [13]:
axial_velocity_df.shape

(3077, 4)

In [14]:
axial_velocity_df.tail()

             z  Q   RPM  axial_velocity
3072  0.973297  4  75.0        0.001203
3073  0.978715  4  75.0        0.001181
3074  0.984133  4  75.0        0.001160
3075  0.989551  4  75.0        0.001138
3076  0.994969  4  75.0        0.001117

In [15]:
axial_velocity_df.to_csv('../../Data/data_16_runs/axial_velocity.csv', index = False)

In [16]:
axial_velocity_df[(axial_velocity_df['Q'] == 5) & (axial_velocity_df['RPM'] == 45)].shape

(181, 4)

Dataset preparation for Diffusion Coefficient prediction

In [17]:
dc = []
with open('../../Data/data_16_runs/diff_coeffs.txt', 'r') as f:
    for line in f:
        dc.append(float(line.strip()))

dc_df = make_diffusion_coefficient_data(velocity_df, dc, mode = 0)
dc_df

    Q   RPM  diffusion_coefficient
0   5  45.0               0.000006
1   5  55.0               0.000006
2   5  65.0               0.000007
3   5  75.0               0.000005
4   3  45.0               0.000005
5   4  45.0               0.000006
6   5  45.0               0.000006
7   6  45.0               0.000005
8   3  55.0               0.000006
9   3  65.0               0.000006
10  3  75.0               0.000006
11  6  55.0               0.000007
12  6  65.0               0.000008
13  6  75.0               0.000007
14  4  55.0               0.000008
15  4  65.0               0.000005
16  4  75.0               0.000008

In [18]:
dc_df.to_csv('../../Data/data_16_runs/diffusion_1_coefficients.csv', index = False)

In [19]:
constants = []

with open('../../Data/data_16_runs/diff_coeffs_181.txt', 'r') as f:
    for line in f:
        constants.append(float(line.strip()))

diffusion_coefficient_df = make_diffusion_coefficient_data(axial_velocity_df, constants, mode = 1)
diffusion_coefficient_df.head()

          z  Q   RPM  diffusion_coefficient
0  0.004722  5  45.0               0.000009
1  0.010347  5  45.0               0.000008
2  0.015973  5  45.0               0.000008
3  0.021597  5  45.0               0.000008
4  0.027219  5  45.0               0.000008

In [20]:
diffusion_coefficient_df.to_csv('../../Data/data_16_runs/diffusion_181_coefficients.csv', index = False)

In [21]:
diffusion_coefficient_df[(diffusion_coefficient_df['Q'] == 5) & (diffusion_coefficient_df['RPM'] == 45.1)]

Empty DataFrame
Columns: [z, Q, RPM, diffusion_coefficient]
Index: []

LOWESS for Large Scale Axial Velocities

In [2]:
df = pd.read_excel('../../Data/v_axial_largescale.xlsx', sheet_name = 'Sheet1')
df.head()

,z,v_ax: DP1,v_ax: DP2,v_ax: DP3,v_ax: DP4,v_ax: DP5,v_ax: DP6,v_ax: DP8,v_ax: DP9,v_ax: DP11,v_ax: DP12,v_ax: DP13,v_ax: DP14,v_ax: DP15,v_ax: DP16,v_ax: DP17,v_ax: DP18,v_ax: DP19,v_ax: DP20
0,0.000003,0.000611,0.002366,0.002735,0.001747,0.002632,0.003047,0.002371,0.002373,0.002352,0.000899,0.002332,0.000465,0.002088,0.003215,0.000687,0.004428,0.001387,0.001360
1,0.004529,0.000552,0.002292,0.002486,0.001795,0.002347,0.003571,0.002513,0.002491,0.002420,0.001011,0.002662,0.000679,0.002355,0.003482,0.000781,0.004663,0.001939,0.001719
2,0.009049,0.000281,0.001846,0.002131,0.001832,0.002147,0.003772,0.002863,0.002831,0.002082,0.001048,0.003166,0.000875,0.002684,0.003739,0.000958,0.004625,0.002110,0.001086
3,0.013557,0.000397,0.001224,0.002294,0.001943,0.002401,0.003813,0.003455,0.003082,0.001934,0.001327,0.003714,0.001056,0.003023,0.003316,0.001054,0.004598,0.001821,0.000507
4,0.018049,0.000330,0.000935,0.002729,0.002316,0.002824,0.003841,0.004014,0.003337,0.001756,0.001798,0.003971,0.001222,0.003133,0.002676,0.001182,0.004175,0.001736,0.000832

In [3]:
df.shape

(231, 19)

In [4]:
df = df[(df['z'] >= 0) & (df['z'] <= 1)]
df.shape

(231, 19)

In [5]:
X = df['z']

data = {'z':X}

for col in df.columns[1:]:
    y = df[col]
    yest = cleveland_lowess(X, y, f = 0.5, iter = 3)
    data[col] = yest

smoothed_df = pd.DataFrame(data)
smoothed_df.head()

,z,v_ax: DP1,v_ax: DP2,v_ax: DP3,v_ax: DP4,v_ax: DP5,v_ax: DP6,v_ax: DP8,v_ax: DP9,v_ax: DP11,v_ax: DP12,v_ax: DP13,v_ax: DP14,v_ax: DP15,v_ax: DP16,v_ax: DP17,v_ax: DP18,v_ax: DP19,v_ax: DP20
0,0.000003,0.004612,0.003225,0.002911,0.003506,0.003393,0.003778,0.003403,0.003132,0.001050,0.002492,0.003360,0.003935,0.003412,0.003037,0.002886,0.003689,0.003175,0.003650
1,0.004529,0.004579,0.003210,0.002906,0.003490,0.003362,0.003763,0.003391,0.003128,0.001056,0.002467,0.003347,0.003921,0.003385,0.003013,0.002885,0.003670,0.003172,0.003634
2,0.009049,0.004546,0.003195,0.002901,0.003474,0.003332,0.003747,0.003380,0.003123,0.001061,0.002443,0.003335,0.003907,0.003357,0.002989,0.002885,0.003652,0.003170,0.003618
3,0.013557,0.004513,0.003180,0.002895,0.003458,0.003302,0.003732,0.003369,0.003119,0.001067,0.002418,0.003322,0.003892,0.003330,0.002964,0.002884,0.003633,0.003167,0.003602
4,0.018049,0.004480,0.003166,0.002890,0.003443,0.003271,0.003717,0.003357,0.003114,0.001072,0.002393,0.003310,0.003878,0.003303,0.002940,0.002883,0.003614,0.003165,0.003586

In [7]:
smoothed_df.to_csv('../../Data/v_axial_largescale_smoothed.csv', index = False)